### ISSUE TITLE
[ENV] ci/cd 구축

### ISSUE THREAD

**Issue by baeksom** [9oormthon-univ/2024_DANPOONG_TEAM_6_BE#1]
# ENV Issue

## Description
GitHub Actions, AWS, Docker를 사용하여 CI/CD 파이프라인을 구축합니다.

## To-do
- [x] AWS 계정 생성 및 배포 초기 환경 세팅
- [x] GitHub Actions 워크플로우 파일 생성
- [x] 도커 파일 생성
- [x] 환경 변수 추가 및 비밀 키 설정
- [x] 파이프라인 테스트
