### ISSUE TITLE
[FEAT] 마이페이지

### ISSUE THREAD

**Issue by baeksom** [9oormthon-univ/2024_DANPOONG_TEAM_6_BE#19]
# ✨Feature Issue

## Description
마이페이지 api 구현입니다.

## To-do
- [ ] 마이페이지 메인(프로필 페이지) : 프로필 사진, 닉네임, 나의 축제 방문 기록
- [ ] 내가 쓴 게시글 목록
- [ ] 알림 설정
- [x] 로그아웃  구현 X -> 프론트에서 jwt 삭제
- [x] 탈퇴하기 -> UserController 에서 구현, User 정보 삭제 및 SecurityContextHolder 삭제
- [ ] 닉네임 변경
